# Import subset of data from postgres to pandas Data Frames

This notebook connects to a postgres database,
storing a snapshot of [this data](https://zenodo.org/record/2592524),
and saves the relevant subset (for us) as pandas dataframes in feather format.
This lets us store ~1GB of data that we use, instead of needing to keep the dozens of GB stored in the db itself.

This lets a larger chunk of the steps be reproducible without the database,
since it brings the data into a shareable size.

In [1]:
import sys
import pandas as pd
from sqlalchemy import create_engine

Edit `config.py` to contain an sqlachemy URL with necessary credentials for your database.

In [2]:
# import db_url from the local configuration file
# edit this file
# for easier handling of secret info
from config import db_url

In [3]:
from sqlalchemy import create_engine
engine = create_engine(
    db_url,
    convert_unicode=True,
    echo=False,
)

In [4]:
%%time
with engine.connect() as connection:
    raw_repositories = pd.read_sql_table('repositories', connection)
raw_repositories

CPU times: user 2.67 s, sys: 590 ms, total: 3.26 s
Wall time: 8.42 s

,id,domain,repository,hash_dir1,hash_dir2,commit,notebooks_count,setups_count,requirements_count,notebooks,setups,requirements,processed,pipfiles_count,pipfile_locks_count,pipfiles,pipfile_locks
0,30957,github.com,psygrammer/psymovie,6f,b6bb40c9f9f38a87d2febeb3bd0683dd69d32c,f413b434c2174f7624ea5ee785f19539c196aa6a,10,0,0,part2/DeepVCat/VideoCat/ch03/03_Accelerating_S...,,,8329,0,0,,
1,30986,github.com,abhishekori/DataStructureAlgoJavaAndPy,fc,c94896131147f5445f8343c087f8cd43bcadeb,328ec73a9183600a5b7e51441f1638d98545face,27,0,0,Untitled1.ipynb;Untitled2.ipynb;Dynamic array ...,,,8329,0,0,,
2,31064,github.com,texib/deeplearning_homework,11,0e1c3071dda4905007da59d275dfc31d9d75e1,bfa4baf45b9525575163a0b61a6d7e488f705f79,25,0,0,muki-batch-keras.ipynb;muki-batch.ipynb;mnist-...,,,8329,0,0,,
3,31199,github.com,jwegas/kaggle_mobile,03,ab0245432b7d69efc8eda37274211edd83825b,7fdb98ded963460132cadb89fe0dac54d8b3ac15,41,0,0,code/get_sparse_data.ipynb;code_old/toPrepareD...,,,8329,0,0,,
4,31261,github.com,ireullin/notes,5b,2e37a9f0ceff8ffdbd376f1c72d6d3d88f97e1,25fd664cec8158c5cc5fc246664ff4c3a92cf72d,70,0,0,search.ipynb;diet/note.ipynb;apache spark cour...,,,8329,0,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265883,234811,github.com,Las-Desire/Cube_Las,4b,d86aa11d53e17881b4106b7e6d28745bdf3fda,1e3669cde89ee0bc865830e9c3bb0b191931e982,11,0,0,Untitled.ipynb;Untitled1.ipynb;2nd level funct...,,,8329,0,0,,
265884,246046,github.com,MAURI-PROGRAM/Data-science-en-cuaderno-Jupyter-,40,a77d547343677a85cfc57f84fb7e22e1aad404,b149901384538dbc2535880ca71f619aa16d9599,9,0,0,Predecir precio de casas/Categorizar/Untitled....,,,8329,0,0,,
265885,239903,github.com,ochiba0227/machineLearning,17,027ec901f2a9ed286e66e2dab6d31854d5b0d5,b4601441b9934b7a93363d5c40eef22dde0baac8,23,0,0,kaggle/all/Untitled.ipynb;kaggle/all/Untitled2...,,,8329,0,0,,
265886,267149,github.com,TimSelf/NetologyHW,51,934a465789b729ad4f1e68f1b136f61cb2cdf6,ea8c185d14cdf6c2d882edf0c87f67f8df46c0f1,59,0,0,Untitled.ipynb;boosting_clean.ipynb;0. Prepara...,,,8329,0,0,,
265887,261475,github.com,mateuschaves/GEOMETRIA-ANALITICA,87,e06af08d7d53a0ae6fcebaa0c60e8bb4a4f098,f4b7f2b2baaae10408fd0370af8dd7065495cdc7,33,0,0,Elipsóide/Questão 1/A.ipynb;Elipsóide/Questão ...,,,8329,0,0,,

In [5]:
%%time
with engine.connect() as connection:
    raw_notebooks = pd.read_sql_table('notebooks', connection)
raw_notebooks

CPU times: user 18.1 s, sys: 2.48 s, total: 20.6 s
Wall time: 33.4 s

,id,repository_id,name,nbformat,kernel,language,language_version,max_execution_count,total_cells,code_cells,...,unknown_cell_formats,empty_cells,processed,skip,sha1_source,homework_count,assignment_count,course_count,exercise_count,lesson_count
0,36579,1684,w11_extensions2/floquet.ipynb,4.1,python3,python,unknown,-1,36,9,...,0,0,32,32,8715429c2cdb93c2d1edf9e21792c26ba0cd57d9,0,0,3,0,0
1,36583,1684,w1_topointro/1D.ipynb,4.1,python3,python,unknown,-1,35,10,...,0,0,32,32,1be7fbddf6823b490ca42494cc7a87038225e631,0,0,1,0,0
2,1127939,197382,KNN.ipynb,4.1,python3,python,3.6.1,11,25,11,...,0,1,131104,0,50bfa9ac086649da23aca4dd6aa54bc4b8208844,0,0,0,0,0
3,1127940,197382,Keras-CNN.ipynb,4.2,python3,python,3.5.2,10,22,11,...,0,1,131104,0,65d4f04f17d5de97d2e43a7eff9f9eaf7da953fe,0,0,0,0,0
4,1127943,197382,LinearRegression.ipynb,4.1,python3,python,3.6.1,4,12,5,...,0,1,131104,0,11a7d4ee556f03d9021515ed4ee9d4f9b008bd8c,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450066,1303633,231143,module1/exercises/TrainAndValidate.ipynb,4.2,python3,python,3.4.5,15,22,11,...,0,0,131104,32,69a9ef5c44adc1d716a5ca6ba1d540a798c64921,0,0,0,-4,0
1450067,1303638,231143,module2/Schedule.ipynb,4.2,python3,python,3.4.5,-1,8,0,...,0,0,32,96,5f9e3cb1fe9507b8c96e55face33749d67679d50,0,0,1,2,0
1450068,1303639,231143,module2/exercises/TrainValTrainTest.ipynb,4.1,python3,python,3.4.5,20,23,11,...,0,0,131104,32,cb8a74003690c89baee8822ba34fa8eff6898738,0,0,0,-2,0
1450069,1303640,231143,module2/labs/CrossValidation.ipynb,4.2,python3,python,3.4.5,-1,26,12,...,0,0,32,32,d10e5d5ed5d76f4e620702eb75bedcc2c3498069,0,0,0,1,0
1450070,1303645,231143,module2/resources/api.ipynb,4.2,python3,python,3.4.5,-1,5,0,...,0,0,32,128,e011bddfd90272f85167df5bf733b1cd1b4fdae3,0,0,0,0,0

We exclude the `msg` column from the executions table, since we aren't analyzing that and it's the majority of all data in the database.

In [6]:
%%time
with engine.connect() as connection:
    raw_executions = pd.read_sql_table('executions', connection, columns=["id", "notebook_id", "mode", "reason", "duration", "repository_id", "skip", "processed"])
raw_executions

CPU times: user 4.91 s, sys: 1.2 s, total: 6.11 s
Wall time: 18.1 s

,id,notebook_id,mode,reason,duration,repository_id,skip,processed
0,235190,359337,5,TypeError,1.328409,48792,0,39
1,235449,783578,5,ImportError,1.323065,125395,0,39
2,235531,538568,5,ImportError,1.325433,80326,0,39
3,265190,1306155,5,ImportError,2.331574,231682,32,39
4,726227,159845,5,None,9.034627,16047,0,35
...,...,...,...,...,...,...,...,...
1168609,1121360,1195113,5,None,2.326676,208865,0,35
1168610,1008062,1337394,5,None,2.322514,237698,32,35
1168611,481513,435887,5,None,15.439874,61401,0,35
1168612,235062,875527,5,ImportError,1.322411,143284,0,39
1168613,95641,963034,3,<Install Dependency Error>,NaN,161488,96,0

All the columns, from which we will load a subset

```
Index(['id', 'notebook_id', 'mode', 'reason', 'msg', 'diff', 'cell', 'count',
       'diff_count', 'timeout', 'duration', 'processed', 'skip',
       'repository_id', 'id', 'repository_id', 'name', 'nbformat', 'kernel',
       'language', 'language_version', 'max_execution_count', 'total_cells',
       'code_cells', 'code_cells_with_output', 'markdown_cells', 'raw_cells',
       'unknown_cell_formats', 'empty_cells', 'processed', 'skip',
       'sha1_source', 'homework_count', 'assignment_count', 'course_count',
       'exercise_count', 'lesson_count', 'id', 'domain', 'repository',
       'hash_dir1', 'hash_dir2', 'commit', 'notebooks_count', 'setups_count',
       'requirements_count', 'notebooks', 'setups', 'requirements',
       'processed', 'pipfiles_count', 'pipfile_locks_count', 'pipfiles',
       'pipfile_locks'],
       ```

Load a joined table of all notebooks, associated with their repos and executions

In [7]:
%%time
column_map = {
    "repositories.repository": "repo",
    "repositories.commit": "commit",
    "notebooks.name": "notebook",
    "executions.reason": "reason",

    "executions.mode": "exmode",
    "executions.skip": "exskip",
    "notebooks.skip": "nbskip",
    "notebooks.language": "language",
    "notebooks.language_version": "language_version",
    "executions.processed": "processed_execution",
    "notebooks.processed": "processed_notebook",
    "repositories.processed": "processed_repo",
    "repositories.setups_count": "setups_count",
    "repositories.setups": "setups",
    "repositories.requirements_count": "requirements_count",
    "repositories.requirements": "requirements",
    "repositories.pipfiles_count": "pipfiles_count",
    "repositories.pipfiles": "pipfiles",
    "repositories.pipfile_locks_count": "pipfile_locks_count",
    "repositories.pipfile_locks": "pipfile_locks",
}
db_columns = list(column_map)

with engine.connect() as connection:
    joined_data = pd.read_sql(
        rf"""
        SELECT {', '.join(db_columns)}
        FROM executions
        RIGHT JOIN notebooks ON executions.notebook_id = notebooks.id
        LEFT JOIN repositories ON notebooks.repository_id = repositories.id
        """,
        connection,
    )
joined_data.columns = [column_map[key] for key in db_columns]
joined_data

CPU times: user 13 s, sys: 2.89 s, total: 15.9 s
Wall time: 40.2 s

,repo,commit,notebook,reason,exmode,exskip,nbskip,language,language_version,processed_execution,processed_notebook,processed_repo,setups_count,setups,requirements_count,requirements,pipfiles_count,pipfiles,pipfile_locks_count,pipfile_locks
0,tambetm/pgexperiments,ad4dada7dfe4c5fb8323597f73129157ede4b5fd,MNIST_PG_running_mean.ipynb,ImportError,5.0,0.0,0,python,2.7.14,39.0,131104,8329,0,,0,,0,,0,
1,JonnyRed/IPython-Notebooks,6675f32167646efbda1df575686de9becf3e4f85,YoungAndFreedman13/Chapter04-Newtons-Laws-of-M...,<Install Dependency Error>,3.0,0.0,0,python,2.7.8,0.0,8224,8329,1,SciPy_SymPy/ipython_doctester/setup.py,1,Numerical-Python/requirements.txt,0,,0,
2,vshaumann/Test,bee2b00d04e0366046e6b25820b43e6ae0a78405,KS Divergence.ipynb,None,5.0,0.0,0,python,3.6.0,35.0,131104,8329,0,,0,,0,,0,
3,Henrilin28/ADS_Final_Homeless,57378e27768bb4627883eef243d892901a174a11,Time series plots/SingleWomenTimesSeries.ipynb,None,5.0,0.0,0,python,2.7.12,35.0,131104,8329,0,,0,,0,,0,
4,luoyuweidu/Script,f0f0bcdfeef66312f73a5c0c9dabeb5fe406a699,ASSO - getting receipts.ipynb,error,5.0,0.0,0,python,2.7.13,39.0,131104,8329,0,,0,,0,,0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1450072,cjwinchester/2018-03-09-nicar-class,7d05fe55e5181aa2c44d8989d2851d22196633e9,completed/18. Setting up Python on your own co...,None,NaN,NaN,416,python,3.6.4,NaN,32,8329,0,,1,requirements.txt,0,,0,
1450073,tjh1997/pandas_exercises,3da2d91d8b4080520d0bccd053fe17bd23c702eb,09_Time_Series/Getting_Financial_Data/Exercise...,None,NaN,NaN,416,python,2.7.11,NaN,32,8329,0,,0,,0,,0,
1450074,pzz2011/demos.ml,3e3f622408859f1f2f791c642f066d00d0e41d4b,jupyter/notebooks/Spark/SparkR/ApacheArrow-Fea...,None,NaN,NaN,128,R,3.3.0,NaN,32,8329,0,,0,,0,,0,
1450075,cfchang/cs591,18d5c7f3db291f8814ec5a2b1f5e9b66528cb44a,Homework-4/4.Food-recipes.ipynb,None,NaN,NaN,96,unknown,unknown,NaN,32,8329,0,,0,,0,,0,
1450076,icodingc/practice-torch,486754cc5ea251f1d2b6324d6aac3f693d36ff59,practical44/practical_requ.ipynb,None,NaN,NaN,0,lua,20100,NaN,32,8329,0,,0,,0,,0,

Now persist these dataframes to .feather files

In [8]:
%%time
joined_data.to_feather("joined-data.feather")
raw_notebooks.to_feather("notebooks.feather")
raw_executions.to_feather("executions.feather")
raw_repositories.to_feather("repositories.feather")

CPU times: user 2.67 s, sys: 1.64 s, total: 4.31 s
Wall time: 6.33 s

In [9]:
!du -hs *.feather

299M	executions.feather
608M	joined-data.feather
371M	notebooks.feather
117M	repositories.feather

And to test how long it takes to load these data back from feather instead of spending minutes querying the database again:

In [10]:
%%time
joined_data = pd.read_feather("joined-data.feather")
raw_notebooks = pd.read_feather("notebooks.feather")
raw_executions = pd.read_feather("executions.feather")
raw_repositories = pd.read_feather("repositories.feather")

CPU times: user 4.62 s, sys: 3.18 s, total: 7.79 s
Wall time: 14.8 s

We only actually need joined-data.feather, which is the joined version of all the other tables, and the one we use in [queries.ipynb](queries.ipynb) to create our task lists.